remote_theme: pmarsceill/just-the-docs

title: SBB API FSS
description: SBB API Financial Systems & Services
baseurl: "/api-fss"
url: "https://sbb-api.github.io"

permalink: pretty
search_enabled: true
heading_anchors: true
aux_links:
    " API FSS on GitHub":
      - "//github.com/sbb-api/api-fss"
